{"name": "Тест. Создание курьера. Ошибка создания. Код 409, \"Этот логин уже используется\"", "status": "passed", "start": 1715602077170, "stop": 1715602078428, "uuid": "fbad19f3-bda9-410b-a6c5-1d3e4f3d2e9a", "historyId": "47cf55da70a17b9dfceb4c625de67e36", "testCaseId": "47cf55da70a17b9dfceb4c625de67e36", "fullName": "tests.test_courier.TestCreateCourier#test_create_courier_exists_login_not_successful", "labels": [{"name": "story", "value": "Тестирование Курьера"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_courier"}, {"name": "subSuite", "value": "TestCreateCourier"}, {"name": "host", "value": "DESKTOP-RJ2RHPG"}, {"name": "thread", "value": "5964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_courier"}]}